service: aws-lambda-crud-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: 'us-west-2'

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
